version: "3.8"
networks:
  alsinet:
    driver: bridge
    external: true
    name: alsinet

services:
  web:
    build: .
    container_name: welbex
    image: welbex
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - alsinet

  postgres:
    image: postgres:15
    container_name: postgres-welbex
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
       - 15432:5432
    networks:
      - alsinet

volumes:
  db-data:
    driver: local
