"""Initial db

Revision ID: 020564bd04fd
Revises: 
Create Date: 2023-05-25 23:06:04.444187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020564bd04fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('town', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pickup_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['pickup_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trucks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trucks')
    op.drop_table('cargos')
    op.drop_table('locations')
    # ### end Alembic commands ###
